//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_DinhQuocDat_Buoi4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_GIA
    {
        public int ID { get; set; }
        public Nullable<int> DienThoaiID { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public string NoiDungDanhGia { get; set; }
        public Nullable<byte> DanhGia { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
    
        public virtual DIEN_THOAI DIEN_THOAI { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
