//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_DinhQuocDat_Buoi4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DQDDbEntities : DbContext
    {
        public DQDDbEntities()
            : base("name=DQDDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_HOA_DON> CT_HOA_DON { get; set; }
        public virtual DbSet<DANH_GIA> DANH_GIA { get; set; }
        public virtual DbSet<DIEN_THOAI> DIEN_THOAI { get; set; }
        public virtual DbSet<HOA_DON> HOA_DON { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<LOAI_DIEN_THOAI> LOAI_DIEN_THOAI { get; set; }
        public virtual DbSet<QUAN_TRI> QUAN_TRI { get; set; }

        public System.Data.Entity.DbSet<K22CNT3_DinhQuocDat_Buoi4.Models.DQDCartItem> DQDCartItems { get; set; }
    }
}
